name: Sync labels

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: EndBug/label-sync@v2.3.3
        with:
          config-file: ./labels.yml
          token: ${{ secrets.GITHUB_TOKEN }}