name: Label Sync

on:
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EndBug/label-sync@v2
        with:
          config-file: labels.yml
          delete-other-labels: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
